
services:
  app:
    build:
      context: ./mesa_24_7_backend
      dockerfile: Dockerfile
    container_name: mesa247_back
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - ./mesa_24_7_backend:/var/www
    depends_on:
      - db
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    command: >
      sh -c "php artisan migrate:fresh --seed --force && php-fpm"
    networks:
      - laravel
  server:
    image: nginx:stable-alpine
    container_name: mesa247_server
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./mesa_24_7_backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
   
    networks:
      - laravel
  
  db:
    image: mysql:8.0
    container_name: mesa247_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mesa247
      MYSQL_USER: psalazar
      MYSQL_PASSWORD: gottopassthistest
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
