
services:
  frontend-prod:
    build:
      context: ./mesa_24_7_frontend
      dockerfile: Dockerfile
    container_name: vue_frontend_prod
    restart: unless-stopped
    ports:
      - '8080:80'
    networks:
      - laravel
  app:
    build:
      context: ./mesa_24_7_backend
      dockerfile: Dockerfile
    container_name: mesa247_back
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - '8000:80'
    depends_on:
      - db
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    command: >
      sh -c "php artisan migrate:fresh --seed --force &&
           apache2-foreground"
    networks:
      - laravel
  
  db:
    image: mysql:8.0
    container_name: mesa247_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mesa247
      MYSQL_USER: psalazar
      MYSQL_PASSWORD: gottopassthistest
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
